### PR TITLE
Add side effects to package.json

### PR DESCRIPTION
**Pull request by denisx**
Add side effects to package.json to help bundlers cut unused code. Good with named imports.

### CODE REVIEW

**Comment by WebReflection** [comment]
I am not sure about this one ... I don't mind adding that extra flags but the underlying issue seems to be bundlers incapable of tree-shaking? 🤔

Or better: what scenario are we trying to solve in here?

**Comment by denisx** [comment]
Package allready has `"type": "module"`. sideEffects just a full settings for bundlers.
For example, if i use named '{serialize} from index', bundler can cut other exports from client bundle.

**Comment by WebReflection** [comment]
@denisx again, that's what my bundler of choice (*rollup*) does already for me ... what is this change trying to solve? which bundler is incapable of proper tree-shaking and requires this change? 🤔

**Comment by denisx** [comment]
yes, more better treeshake. https://rollupjs.org/configuration-options/#treeshake-modulesideeffects

**Pull request merged**
