### PR TITLE
Add command to generate .d.ts files for cjs and esm from JSDoc comments

### PR DESCRIPTION
**Pull request by andrew-pyle**
Add a script to generate .d.ts files for the esm/index.js and cjs/index.js at the end of the `npm run build` script. This PR is inspired by comment https://github.com/ungap/structured-clone/issues/3#issuecomment-1005497915

@WebReflection Once I ran the script locally, it appears that the existing JSDoc is not totally valid. Examples:

```ts
// index.d.ts

/**
 * a type representation
 */
export type Record = Array<string, any>; // Generic type 'Array<T>' requires 1 type argument(s). ts(2314)

// Created from index.js
/**
 * @typedef {Array<string,any>} Record a type representation ← 💥 Array should only have one type argument, right?
 */
```
And
```ts
// serialize.d.ts

// Property 'json' does not exist on type '{ lossy?: boolean | undefined; }'. ts(2339)
export function serialize(value: any, { json, lossy }?: {
    lossy?: boolean;
} | null): Record[];

// Created from serialize.js

/**
 * Returns an array of serialized Records.
 * @param {any} value a serializable value.
 * @param {{lossy?: boolean}?} options an object with a `lossy` property that, ← 💥 JSDoc type doesn't include `json`
 *  if `true`, will not throw errors on incompatible types, and behave more
 *  like JSON stringify would behave. Symbol and Function will be discarded.
 * @returns {Record[]}
 */
 export const serialize = (value, {json, lossy} = {}) => {
  const _ = [];
  return serializer(!(json || lossy), !!json, new Map, _)(value), _;
};
```

I'd be glad to update the JSDoc type signatures, but I didn't want to assume the author's intention without checking.

How should we proceed?

### CODE REVIEW

**Comment by WebReflection** [comment]
I suck at TS so please update any definition but keep in mind this module has an extra argument which is not standard (yet?)

**Comment by andrew-pyle** [comment]
👍

@WebReflection What is the extra argument? As best I can tell, the [standard signature](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) is as follows.
```ts
structuredClone(value: any, options: { transfer: Transferable[] })

type Transferable = 
  | ArrayBuffer
  | MessagePort
  | ReadableStream
  | WritableStream
  | TransformStream
  | AudioData
  | ImageBitmap
  | VideoFrame
  | OffscreenCanvas
  | RTCDataChannel
```

I see the `{ transfer }` option in the second parameter to `structuredClone()`. Is that the extra argument you referenced for this module?

**Comment by andrew-pyle** [comment]
@WebReflection Would you be opposed to writing `.d.ts` files by hand instead of JSDoc comments? They are more expressive than JSDoc, but I will defer to your preferences, of course.

**Comment by andrew-pyle** [comment]
OK, so to use JSDoc type definitions we need to
1. Generate .d.ts files → typescript compiler does this
2. Export the .d.ts files for ESM and for CJS → package.json does this

There are several complicated things I needed to do because of using JSDoc types
- dynamic import of the shared type definitions, instead of static imports. JSDoc doesn't export types without JS side-effects. We could use static imports with authored `.d.ts` files.
- Set up the typescript compiler in the build step. We could avoid this step with authored `.d.ts` files.
- We register the type files in `package.json`, so that the CJS files would get the same types as the ESM. The Typescript compiler didn't seem to understand the JSDoc properly within the CJS default export. `Object.defineProperty(exports, '__esModule', {value: true}).default = ...`. With authored `.d.ts` files, we could either do this same thing, or write two copies of the `.d.ts` file, one for CJS and one for ESM.

And I see that the build check failed, so I will need to see why the Typescript compiler isn't happy.

**Comment by WebReflection** [comment]
Manual .d.ts is fine to me, but keep in mind not all primitive are supported in here and transferable is actively ignored when the polyfill is used instead of the builtin function. It’s complicated, I suppose

**Comment by andrew-pyle** [comment]
@WebReflection OK I rewrote the types as .d.ts files in the `esm/` folder. I added a node script to copy the .d.ts files into the `cjs/` folder. I added that script to the `npm build` command.

Also, please review the `Cloneable` type in the `esm/internal.d.ts` file. This is the type which  all three methods can handle.
- `structuredClone`
- `serialize`
- `deserialize`

Is the type accurate? I tried to be as precise as possible, starting with MDN, and then removing types which the README says are not supported yet.

I also added a comment in the `index.d.ts` file about ignoring the `transfer` option. Maybe that's not necessary, since it's in the README. Maybe I should just take that out, so it doesn't get out of date?

Finally, the types only work properly when the consumer is using typescript with es2015 or later. I made a note in the README for that.

**Comment by WebReflection** [comment]
@andrew-pyle awesome PR, thank you! I think it wasn't necessary to copy into cjs folder types as these can be defined at the package.json level, which I just did, but TL;DR the module is now published with your changes 🍻

**Pull request merged**
